image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test
    
before_script:
    - dotnet --version
    - dotnet restore
    
build:
    stage: build
    script:
       - dotnet build CIModel
       - dotnet build CIPersistence
        
test:
    stage: test
    script:
        - dotnet test Test
